name: Monitor and Cleanup CloudFormation Stacks

on:
  workflow_dispatch: # Permite la ejecución manual del workflow

jobs:
  monitor-and-clean:
    name: Monitor and Cleanup Stacks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Setup AWS Credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Scan and Delete Stacks
        run: |
          echo "Scanning CloudFormation stacks..."
          STACKS=$(aws cloudformation list-stacks --stack-status-filter ROLLBACK_COMPLETE --query "StackSummaries[*].StackName" --output text)
          
          if [ -z "$STACKS" ]; then
            echo "No stacks in ROLLBACK_COMPLETE state found."
          else
            for STACK in $STACKS; do
              echo "Deleting stack: $STACK"
              aws cloudformation delete-stack --stack-name $STACK
              echo "Deletion initiated for stack: $STACK"
            done
          fi
