name: Deploy AWS Infraestructure

on:
  push:
    branches:
      - main
      - task/*

jobs:

  # Stage: Validate templates
  validate-templates:
    name: Validate templates
    needs: setup-aws
    runs-on: ubuntu-latest
    strategy:
      matrix:
        template:
          - { name: template-VPC.yaml, params: parameters-VPC.json }
          - { name: template-EC2.yaml, params: parameters-EC2.json }
          - { name: template-RDS.yaml, params: parameters-RDS.json }
          - { name: template-S3.yaml, params: parameters-S3.json }
    steps:
      - name: Setup AWS Credentials
        uses: ./.github/workflows/setup-aws-account.yml
        with:
          region: us-east-1

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Validate CloudFormation Template
        run: |
          aws cloudformation validate-template --template-body file://AWS_Cloudformation/templates/${{ matrix.template.name }} --region us-east-1

  # Stage: Deploy of templates
  deploy-templates:
    name: Deploy templates
    needs: validate-templates
    runs-on: ubuntu-latest
    strategy:
      matrix:
        template:
          - { name: template-VPC.yaml, params: parameters-VPC.json, stack: Lab-VPC-Stack }
          - { name: template-EC2.yaml, params: parameters-EC2.json, stack: Lab-EC2-Stack }
          - { name: template-RDS.yaml, params: parameters-RDS.json, stack: Lab-RDS-Stack }
          - { name: template-S3.yaml, params: parameters-S3.json, stack: Lab-S3-Stack }
    steps:
      - name: Setup AWS Credentials
        uses: ./.github/workflows/setup-aws-account.yml
        with:
          region: us-east-1

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy CloudFormation Template
        run: |
          aws cloudformation deploy \
            --template-file AWS_Cloudformation/templates/${{ matrix.template.name }} \
            --stack-name ${{ matrix.template.stack }} \
            --parameter-overrides file://AWS_Cloudformation/parameters/${{ matrix.template.params }}
