name: Setup AWS Account

on:
  workflow_call:
    inputs:
      region:
        required: true
        type: string

jobs:
  setup-aws:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ inputs.region }}

      - name: Verify AWS credentials
        run: aws sts get-caller-identity
